# Anchor 框架相关配置
[features]
seeds = false
skip-lint = false
[programs.localnet]
# 指定合约部署地址（就是如果合约部署就使用该地址）
hw_06_anchor_simple = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# 指定合约部署时所使用的钱包
wallet = "/home/chiangfire/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 100000
